tweeterproject3/tweet/urls.py
from django.urls import path
from . import views

app_name = "tweet"

urlpatterns = [
    path('', views.home, name="homepage"),
    path('create/', views.createpost, name="createpost"),
    path('edit/<int:postid>/', views.editpost, name="editpost"),
    path('del/<int:postid>/', views.delpost, name="delpost"),

    path('register/', views.register, name="register")
]

tweeterproject3/tweeterproject3/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tweet.urls")),

    path('accounts/', include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweeterproject3/tweet/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    content = models.TextField(max_length=240)
    image = models.ImageField(upload_to="photos/")
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username+" "+str(self.created_at)

tweeterproject3/tweet/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class TweetForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'image']


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

tweeterproject3/tweet/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import TweetForm, UserRegistrationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login

# Create your views here.
def home(request):
    posts = Post.objects.order_by('-created_at')
    return render(request, "home.html", {"posts":posts})

@login_required
def createpost(request):
    if request.method=="POST":
        form = TweetForm(request.POST, request.FILES)
        if form.is_valid():
            tweet = form.save(commit=False)
            tweet.user = request.user
            tweet.save()

            return redirect("/")
    else:
        form = TweetForm()

    return render(request, "createpost.html", {"form":form})

@login_required
def editpost(request, postid):
    post_inst = get_object_or_404(Post, id=postid, user=request.user)
    if request.method=="POST":
        form = TweetForm(request.POST, request.FILES, instance=post_inst)
        tweet = form.save(commit=False)
        tweet.user = request.user
        tweet.save()

        return redirect("/")
    else:
        form = TweetForm(instance=post_inst)

    return render(request, "editpost.html", {"form":form})

def delpost(request, postid):
    post = get_object_or_404(Post, id=postid, user=request.user)
    post.delete()

    return redirect("/")


def register(request):
    if request.method=="POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            login(request, user)
            return redirect("/")
    else:
        form = UserRegistrationForm()

    return render(request, "registration/register.html", {"form":form})

tweeterproject3/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django Tailwind</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% tailwind_css %}
</head>

<body class="bg-gray-50 text-black font-serif leading-normal tracking-normal">

    <div class="toast toast-top toast-end">
        <div class="alert alert-info">
            <span>Hello from daisyUi 👋</span>
        </div>
    </div>

<div class="container mx-auto">
    <section class="flex items-center justify-center h-screen">
        <h1 class="text-5xl">Django + Tailwind = ❤️</h1>
    </section>
</div>
</body>
</html>

tweeterproject3/tweet/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load tailwind_tags %}
    {% tailwind_css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">

    <style>
        input, textarea{
            border:1px solid gray;
            border-radius:0.2rem;
        }
    </style>
</head>
<body>
    <div class="w-full h-full flex flex-col">

        <nav class="navbar navbar-expand-lg bg-gray-300">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="/create/">Create</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>

                    {% if user.is_authenticated %}
                        <form class="d-flex" action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-secondary" type="submit">Logout</button>
                        </form>
                    {% else %}
                        <a href="{% url 'tweet:register' %}" class="btn btn-info">Register</a>
                        <a href="/accounts/login/" class="btn btn-success">Login</a>
                    {% endif %}

                </div>
            </div>
        </nav>
        
        {% block body %}

        {% endblock %}

    </div>
</body>
</html>

tweeterproject3/tweet/templates/createpost.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block body %}
    <p class="w-full h-5"> </p>
    <div class="w-full h-max flex flex-col items-center">
        <form method="post" enctype="multipart/form-data" class="w-1/3 h-max flex flex-col gap-3">
            {% csrf_token %}

            {% for field in form %}
            {{field.as_field_group}}
            {% endfor %}

            <div class="flex flex-row gap-3">
                <button type="submit" class="btn btn-success w-max">Create post</button>
                <a href="/" class="btn btn-danger w-max">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

tweeterproject3/tweet/templates/editpost.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block body %}
    <p class="w-full h-5"> </p>
    <div class="w-full h-max flex flex-col items-center">
        <form method="post" class="w-1/3 h-max flex flex-col gap-3">
            {% csrf_token %}

            {% for field in form %}
            {{field.as_field_group}}
            {% endfor %}

            <div class="flex flex-row gap-3">
                <button type="submit" class="btn btn-success w-max">Save changes</button>
                <a href="/" class="btn btn-danger w-max">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

tweeterproject3/tweet/templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block body %}

    {% if user.is_authenticated %}
    <p class="text-center w-full text-2xl">Welcome {{user}}</p>
    {% endif %}

    <p class="w-full h-5"> </p>
    
    <div class="w-full h-max flex flex-row gap-2 wrap">
        {% for i in posts %}
        <div class="card" style="width: 18rem;">
            <img src="{{i.image.url}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{i.user.username}}</h5>
                <p class="card-text">{{i.content}}</p>
                
                {% if i.user == user %}
                <div class="w-full flex flex-row gap-3">
                    <a href="{% url 'tweet:editpost' i.id %}" class="btn btn-primary shadow-none">Edit</a>
                    <a href="{% url 'tweet:delpost' i.id %}" class="btn btn-danger">Delete</a>
                </div>

                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}